import { createContext, useContext, useState, type ReactNode } from "react";

type Lang = "ru" | "en";

const translations = {
  ru: {
    // Header
    menu: "Меню",
    categories: "Категории",
    offers: "Акции",
    restaurants: "Рестораны",
    cart: "Корзина",
    account: "Аккаунт",
    // Hero
    heroTitle: "Вкус Африки\nс доставкой.",
    heroSubtitle: "Лучшие африканские блюда вашего города — горячие, свежие, за 30 минут.",
    orderNow: "Заказать сейчас",
    viewMenu: "Смотреть меню",
    // Categories
    popular: "Популярные",
    popularDesc: "Самые заказываемые блюда",
    grillades: "Гриль",
    grilladesDesc: "Курица, мясо на огне",
    traditionalDishes: "Традиционные блюда",
    traditionalDesc: "Рис, соусы, африканские рецепты",
    streetFood: "Стрит-фуд",
    streetFoodDesc: "Алоко, брошетт, быстрые закуски",
    desserts: "Десерты",
    dessertsDesc: "Бенье, кокос, банановые сладости",
    drinks: "Напитки",
    drinksDesc: "Биссап, имбирь, натуральные соки",
    combo: "Комбо",
    comboDesc: "Блюдо + напиток, выгодные наборы",
    discover: "Открыть",
    // Live tracker
    live: "В прямом эфире",
    nextDelivery: "Следующая доставка",
    min: "мин",
    restaurantToYou: "Ресторан → Вы",
    // Stats
    today: "Сегодня",
    avgTime: "Среднее время",
    satisfaction: "Удовлетворённость",
    // Flash offer
    discount: "-20%",
    africanCuisine: "Африканская Кухня",
    seeAll: "Все",
    // Filters
    filters: "Фильтры",
    yourCravings: "Ваши предпочтения",
    vegetarian: "Вегетарианское",
    fast: "Быстрое",
    starred: "Со звездой",
    healthyFilter: "Полезное",
    newFilter: "Новинки",
    // Cart
    myCart: "Моя корзина",
    checkOrder: "Проверьте заказ перед оформлением.",
    emptyCart: "Ваша корзина пуста",
    total: "Итого",
    order: "Заказать",
    currency: "₽",
    // Dishes
    jollofSpecial: "Джолоф Специальный",
    mafeClassic: "Мафе Классик",
    thiebRoyal: "Тьебудьен Роял",
    // Address
    addressPlaceholder: "Введите ваш адрес доставки",
    deliveryAddress: "Адрес доставки",
    // About
    aboutTag: "О нас",
    aboutTitle: "Союз двух культур",
    aboutDesc: "Солнце Африки — это проект, рождённый из желания познакомить Россию с богатством африканской кухни. Мы не просто готовим — мы адаптируем аутентичные рецепты для русского вкуса, создавая уникальный союз двух культур. Это больше, чем еда — это мост между континентами, созданный для удовольствия каждого.",
    aboutValue1Title: "Культурный мост",
    aboutValue1Desc: "Мы объединяем африканские традиции и русские вкусы в каждом блюде — настоящий брак культур.",
    aboutValue2Title: "С любовью к каждому",
    aboutValue2Desc: "Каждый рецепт адаптирован с заботой, чтобы вы открыли новые вкусы без границ.",
    aboutValue3Title: "Аутентичные рецепты",
    aboutValue3Desc: "Настоящие африканские блюда, приготовленные с уважением к традициям и свежими ингредиентами.",
    // Footer
    footerTagline: "Вкус Африки, адаптированный для России. Союз двух культур на вашем столе.",
    footerNav: "Навигация",
    footerAbout: "О нас",
    footerContact: "Контакты",
    footerAddress: "Москва, ул. Примерная, 12",
    footerHours: "Ежедневно 10:00 — 23:00",
    footerApp: "Приложение",
    footerAppDesc: "Скачайте наше приложение для быстрого заказа и эксклюзивных предложений.",
    footerDownload: "Скачать в",
    footerRights: "Все права защищены.",
    footerPrivacy: "Политика конфиденциальности",
    footerTerms: "Условия использования",
    footerCookies: "Файлы cookie",
    // Menu page
    menuPageTitle: "Наше меню",
    menuPageSubtitle: "Выберите ваше африканское блюдо — каждое приготовлено с душой.",
    allDishes: "Все",
    addToCart: "Добавить",
    clearFilters: "Сбросить",
    noResults: "Ничего не найдено. Попробуйте другие фильтры.",
    // Categories page
    categoriesPageTitle: "Категории",
    categoriesPageSubtitle: "Исследуйте все вкусы Африки — выберите свою категорию.",
    dishesCount: "блюд",
    prevCategory: "Предыдущая",
    nextCategory: "Следующая",
    // Offers page
    offersPageTitle: "Акции и скидки",
    offersPageSubtitle: "Лучшие предложения — не упустите свой шанс!",
    promoOfTheDay: "Акция дня",
    endsIn: "Осталось",
    moreDeals: "Ещё предложения",
    // Cart page
    itemsInCart: "товаров в корзине",
    deliveryMode: "Способ получения",
    deliveryOption: "Доставка",
    pickupOption: "Самовывоз",
    free: "Бесплатно",
    chooseTime: "Выберите время",
    slotRequired: "Выберите время получения",
    deliveryInfo: "Данные доставки",
    contactInfo: "Контактные данные",
    phoneLabel: "Телефон",
    phonePlaceholder: "+7 (___) ___-__-__",
    phoneError: "Введите корректный номер телефона",
    commentLabel: "Комментарий",
    commentPlaceholder: "Пожелания к заказу...",
    addressError: "Введите адрес доставки (мин. 5 символов)",
    subtotal: "Подитог",
    deliveryFee: "Доставка",
    timeSlot: "Время",
    placeOrder: "Оформить заказ",
    orderConfirmed: "Заказ оформлен!",
    orderConfirmedDesc: "Спасибо! Мы готовим ваш заказ. Ожидайте звонка для подтверждения.",
    backToHome: "На главную",
    goToCart: "Перейти в корзину",
    // Account page
    accountPageTitle: "Мой аккаунт",
    accountPageSubtitle: "Управляйте своим профилем и заказами.",
    loginTitle: "Войти",
    loginBtn: "Войти",
    password: "Пароль",
    orContinueWith: "или продолжить с",
    noAccount: "Нет аккаунта?",
    registerLink: "Зарегистрироваться",
    registerTitle: "Регистрация",
    registerBtn: "Создать аккаунт",
    hasAccount: "Уже есть аккаунт?",
    loginLink: "Войти",
    firstName: "Имя",
    lastName: "Фамилия",
    editProfile: "Редактировать профиль",
    defaultAddress: "Адрес по умолчанию",
    saveProfile: "Сохранить",
    saved: "Сохранено ✓",
    logout: "Выйти",
  },
  en: {
    menu: "Menu",
    categories: "Categories",
    offers: "Offers",
    restaurants: "Restaurants",
    cart: "Cart",
    account: "Account",
    heroTitle: "Taste of Africa\ndelivered.",
    heroSubtitle: "The best African dishes in your city — hot, fresh, in 30 minutes.",
    orderNow: "Order now",
    viewMenu: "View menu",
    popular: "Popular",
    popularDesc: "Most ordered dishes",
    grillades: "Grills",
    grilladesDesc: "Chicken, meat on fire",
    traditionalDishes: "Traditional Dishes",
    traditionalDesc: "Rice, sauces, African recipes",
    streetFood: "Street Food",
    streetFoodDesc: "Alloco, skewers, quick bites",
    desserts: "Desserts",
    dessertsDesc: "Beignets, coconut, banana sweets",
    drinks: "Drinks",
    drinksDesc: "Bissap, ginger, natural juices",
    combo: "Combo",
    comboDesc: "Meal + drink, great value sets",
    discover: "Discover",
    live: "Live",
    nextDelivery: "Next delivery",
    min: "min",
    restaurantToYou: "Restaurant → You",
    today: "Today",
    avgTime: "Avg time",
    satisfaction: "Satisfaction",
    discount: "-20%",
    africanCuisine: "African Cuisine",
    seeAll: "See all",
    filters: "Filters",
    yourCravings: "Your cravings",
    vegetarian: "Vegetarian",
    fast: "Fast",
    starred: "Starred",
    healthyFilter: "Healthy",
    newFilter: "New",
    myCart: "My Cart",
    checkOrder: "Review your order before continuing.",
    emptyCart: "Your cart is empty",
    total: "Total",
    order: "Order",
    currency: "₽",
    jollofSpecial: "Jollof Special",
    mafeClassic: "Mafé Classic",
    thiebRoyal: "Thiéboudienne Royal",
    addressPlaceholder: "Enter your delivery address",
    deliveryAddress: "Delivery address",
    aboutTag: "About us",
    aboutTitle: "A union of two cultures",
    aboutDesc: "Солнце Африки was born from the desire to introduce Russia to the richness of African cuisine. We don't just cook — we adapt authentic recipes for Russian tastes, creating a unique marriage of two cultures. It's more than food — it's a bridge between continents, made for the enjoyment of all.",
    aboutValue1Title: "Cultural bridge",
    aboutValue1Desc: "We blend African traditions with Russian palates in every dish — a true marriage of cultures.",
    aboutValue2Title: "Made with love",
    aboutValue2Desc: "Every recipe is carefully adapted so you can discover new flavors without borders.",
    aboutValue3Title: "Authentic recipes",
    aboutValue3Desc: "Real African dishes prepared with respect for tradition and the freshest ingredients.",
    footerTagline: "The taste of Africa, adapted for Russia. A union of two cultures on your table.",
    footerNav: "Navigation",
    footerAbout: "About us",
    footerContact: "Contact",
    footerAddress: "Moscow, Primernaya St., 12",
    footerHours: "Daily 10:00 AM — 11:00 PM",
    footerApp: "Our App",
    footerAppDesc: "Download our app for fast ordering and exclusive deals.",
    footerDownload: "Get it on",
    footerRights: "All rights reserved.",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    footerCookies: "Cookies",
    // Menu page
    menuPageTitle: "Our Menu",
    menuPageSubtitle: "Choose your African dish — each one crafted with soul.",
    allDishes: "All",
    addToCart: "Add",
    clearFilters: "Clear",
    noResults: "Nothing found. Try different filters.",
    // Categories page
    categoriesPageTitle: "Categories",
    categoriesPageSubtitle: "Explore all the flavors of Africa — choose your category.",
    dishesCount: "dishes",
    prevCategory: "Previous",
    nextCategory: "Next",
    // Offers page
    offersPageTitle: "Deals & Discounts",
    offersPageSubtitle: "Best offers — don't miss your chance!",
    promoOfTheDay: "Deal of the Day",
    endsIn: "Ends in",
    moreDeals: "More deals",
    // Cart page
    itemsInCart: "items in cart",
    deliveryMode: "Delivery method",
    deliveryOption: "Delivery",
    pickupOption: "Pickup",
    free: "Free",
    chooseTime: "Choose time",
    slotRequired: "Please select a time slot",
    deliveryInfo: "Delivery details",
    contactInfo: "Contact details",
    phoneLabel: "Phone",
    phonePlaceholder: "+7 (___) ___-__-__",
    phoneError: "Enter a valid phone number",
    commentLabel: "Comment",
    commentPlaceholder: "Order notes...",
    addressError: "Enter a delivery address (min 5 chars)",
    subtotal: "Subtotal",
    deliveryFee: "Delivery",
    timeSlot: "Time",
    placeOrder: "Place order",
    orderConfirmed: "Order placed!",
    orderConfirmedDesc: "Thank you! We're preparing your order. Expect a confirmation call soon.",
    backToHome: "Back to home",
    goToCart: "Go to cart",
    // Account page
    accountPageTitle: "My Account",
    accountPageSubtitle: "Manage your profile and orders.",
    loginTitle: "Sign in",
    loginBtn: "Sign in",
    password: "Password",
    orContinueWith: "or continue with",
    noAccount: "Don't have an account?",
    registerLink: "Sign up",
    registerTitle: "Sign up",
    registerBtn: "Create account",
    hasAccount: "Already have an account?",
    loginLink: "Sign in",
    firstName: "First name",
    lastName: "Last name",
    editProfile: "Edit profile",
    defaultAddress: "Default address",
    saveProfile: "Save",
    saved: "Saved ✓",
    logout: "Log out",
  },
} as const;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Record<string, string>;
}

const fallbackContext: LanguageContextType = {
  lang: "ru",
  setLang: () => undefined,
  t: translations.ru as Record<string, string>,
};

const LanguageContext = createContext<LanguageContextType>(fallbackContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("ru");
  const t = translations[lang] as Record<string, string>;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
